### ISSUE TITLE
Recoverable fatal error in akismet_data_report_multiple when deleting user + content

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/akismet#3]
When I try to delete a user + their content at the same time, I get the following fatal eror:

```
Recoverable fatal error: Argument 2 passed to akismet_data_report_multiple() must be of the type array, null given, called in backdrop/modules/contrib/akismet/akismet.module on line 2386 and defined in akismet_data_report_multiple() (line 490 of backdrop/modules/contrib/akismet/akismet.module).
```

**Comment by idflorin** [comment]
I have the same error plus:
`Notice: Undefined index: accounts in akismet_form_user_multiple_cancel_confirm_submit() (line 2384 of /home/topexpensivecar/public_html/modules/akismet/akismet.module).
Warning: array_keys() expects parameter 1 to be array, null given in akismet_form_user_multiple_cancel_confirm_submit() (line 2384 of /home/topexpensivecar/public_html/modules/akismet/akismet.module).`
