### ISSUE TITLE
Fatal error due bracket array syntax

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/akismet#7]
I got a fatal error and whitescreen on all site pages when updated to latest Akismet. `Parse error: syntax error, unexpected '[' in /home/mysite/public_html/modules/akismet/akismet.class.inc on line 460`

Line 460: `$parameters = ['key' => $key...`

Akismet is using the square bracket array syntax, my website is on old PHP. We need to support older PHP versions still.

**Comment by herbdool** [comment]
Sorry I didn't see this earlier. I'm going to close now since the minimum supported version of Backdrop now allows the square bracket.
